### ISSUE TITLE
User on CUPS print server image: container always restarts

### ISSUE THREAD

**Issue by Florent8** [olbat/dockerfiles#32]
I want to use this configuration:
```yaml
cups:
    container_name: sf4_cups
    image: olbat/cupsd
    ports:
      - 631:631
    restart: always
    volumes:
      - .docker/cups/printers.conf:/etc/cups/printers.conf
````
But the mounting file `printers.conf` has its rights which change to root:<br/>
![root](https://user-images.githubusercontent.com/15065422/80374660-4bb7d700-8897-11ea-9e21-d2aceaf44857.PNG)

So, I trie to add `user` to config:
```yaml
cups:
    container_name: sf4_cups
    image: olbat/cupsd
    ports:
      - 631:631
    restart: always
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .docker/cups/printers.conf:/etc/cups/printers.conf
````
But with this configuration, the container always restarts:<br/>
![docker_ps](https://user-images.githubusercontent.com/15065422/80374860-a3564280-8897-11ea-8fca-4b490f69b30b.PNG)
